#!/bin/bash

set -eu
set -o pipefail


################################################################################

function logged-in {
    if ! out="$(kubectl auth whoami 2>&1)"; then
        echo "${out}" >&2
        return 2
    fi
}

function ensure-context {
    local err

    err="error: current-context is not set"
    if [ "$(kubectl config current-context 2>&1)" = "${err}" ]; then
        echo "Choose context!"
        kubectl context >/dev/null
    fi
}

function get-namespaces {
    local err

    if ! logged-in; then
        return 2
    fi

    kubectl get namespaces --no-headers -o name | xargs -n1 basename
}

function set-namespace {
    local namespace

    namespace="${1}"

    if [ "${namespace}" = "-" ]; then
        namespace=""
    fi
    kubectl config set-context --current --namespace="${namespace}"
}

function do-complete {
    if [ "${#}" -lt 2 ] && logged-in; then
        get-namespaces
    else
        # It's very unclear why ":4" specifically turns off further completions.
        # But it does.
        # See: https://github.com/kubernetes/kubernetes/commit/09bbe37ce6043b0e
        echo :4
    fi
}

################################################################################

function usage {
    local name

    name=$(basename "${0}" | tr "-" " ")

    cat <<EOM
Usage: ${name} [-h | --help] [ -l | --list ] [NAMESPACE|-]

  -h, --help    Show this help message.

EOM
}

function namespace-main {
    local o name opts long
    local -a namespaces=()
    local opt_help opt_list

    name="$(basename "${0}")"
    opts="hl"
    long="help,list"
    o="$(getopt -o "${opts}" -l "${long}" -n "${name}" -- "${@}")"
    eval set -- "${o}"

    while true; do
        case "${1}" in
            -h | --help) shift; opt_help=true                                 ;;
            -l | --list) shift; opt_list=true                                 ;;
            -- )         shift; break                                         ;;
            * )                 break                                         ;;
        esac
    done

    if [ "${opt_help:-}" = true ]; then
        usage
        exit
    fi

    if [ "${opt_list:-}" = true ]; then
        kubectl config current-context >/dev/null
        get-namespaces
        exit
    fi

    ensure-context

    case "${1:-}" in
        '') mapfile -t namespaces < <(get-namespaces); wait $!
            set-namespace "$( printf "%s\n" "${namespaces[@]}"                 \
                            | fzf --ansi --height $(( ${#namespaces[@]} + 2))  \
                            )"
            ;;
        *)  set-namespace "${1}"                                              ;;
    esac
}

function main {
    case "$(basename "${0}")" in
        kubectl_complete-*)   do-complete      "${@}" ;;
        *)                    namespace-main   "${@}" ;;
    esac
}

main "${@}"; exit
