#!/bin/bash

################################################################################

set -euo pipefail

function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function error-usage {
    error "${*}"
    echo
    usage
    return 2
}

################################################################################


function k8s {
    kubectl ${OPT_CTX:+--context=${OPT_CTX}} "${@}"
}

function k8s-logged-in {
    if ! out="$(k8s auth whoami 2>&1)"; then
        echo "${out}" >&2
        return 2
    fi
}

################################################################################

function filter-flags {
    for arg in "${@}"; do
        case "${arg}" in
            -*) ;;
            *)  echo "${arg}";;
        esac
    done
}

function k8s-query-secrets {
    local query

    query="${1}"

    if kubectl auth whoami &>/dev/null; then
        kubectl get secrets -o json | jq -r "${query}"
    fi
}

function do-complete-show {
    local secret qname

    secret="${1:-}"
    field="${2:-}"

    case "${#}" in
        0|1) k8s-query-secrets ".items[] | .metadata.name"                    ;;
        2) qname="select(.metadata.name == \"${secret}\")"
           k8s-query-secrets ".items[] | ${qname} | .data | keys[]"
           ;;
        *) echo :4                                                            ;;
    esac
}

# TODO: Read and use the --context flag for completions
function do-complete {
    local args cmd secret field

    mapfile -t args < <(filter-flags "${@}"); wait $!

    cmd="${args[0]:-}"

    case "${#args[@]}" in
        1) printf '%s\n' list show copy                                       ;;
        *) case "${cmd}" in
               show|copy) do-complete-show "${args[@]:1}"                     ;;
               *)         echo :4                                             ;;
           esac                                                               ;;
    esac
}

################################################################################

function usage {
    cat <<EOM
Usage: $(basename "${0}") [-h | --help] <CMD> <ARGS>

  -h, --help           Show this help message.
  -d, --decode         Decode base64 encoded values.
  -c, --context=<CTX>  Use CTX as kubectl context.

Where CMD is one of

  list                   — List all secrets and their fields.
  show <SECRET> <FIELD>  — Show a FIELD in a SECRET.
  copy <SECRET> <FIELD>  — Copy a FIELD in a SECRET.

EOM
}

function secret-show {
    local secret field query

    secret="${1}"
    field="${2}"

    query=".data.\"${field}\""
    if [ "${OPT_DECODE}" = true ]; then
        query+=' | @base64d'
    fi

    k8s-logged-in
    k8s get secret "${secret}" -o json | jq -r "${query}"
}

function secret-copy {
    k8s-logged-in

    secret-show "${@}" | wl-copy -n

    read -rp "Copied secret …"
    wl-copy -c
}

function secret-list {
    k8s-logged-in

    k8s get secrets -o json | jq -r ' .items[]
                                    | .metadata.name
                                    + ":\n  - "
                                    + (.data | keys | join("\n  - "))
                                    '
}

function secret {
    local o name opts long
    local cmd OPT_CTX

    name="$(basename "${0}")"
    opts="hc:d"
    long="help,context:,decode"
    o="$(getopt -o "${opts}" -l "${long}" -n "${name}" -- "${@}")"
    eval set -- "${o}"

    OPT_CTX=
    OPT_DECODE=false

    while true; do
        case "${1}" in
            -h | --help)
                usage
                exit
                ;;

            -c | --context)
                OPT_CTX="${2}"
                shift 2
                ;;

            -d | --decode)
                OPT_DECODE=true
                shift
                ;;

            -- ) shift; break ;;
            * ) break ;;
        esac
    done

    export OPT_CTX

    cmd="${1:-}"

    case "${cmd}" in
        list) secret-list "${@:2}"                                            ;;
        show) secret-show "${@:2}"                                            ;;
        copy) secret-copy "${@:2}"                                            ;;
        '')   error-usage "Missing command!"                                  ;;
        *)    error-usage "Unknown command '${cmd}'!"                         ;;
    esac
}

function main {
    case "$(basename "${0}")" in
        kubectl_complete-*)   do-complete    "${@}"                           ;;
        *)                    secret         "${@}"                           ;;
    esac
}

main "${@}"; exit
