#!/bin/bash

set -euo pipefail

declare -A COMMANDS=(
    [api-resources]=""
    [api-versions]=""
    [cluster-info]=""
    [describe]=""
    [diff]=""
    [events]=""
    [get]=""
    [version]=""
)

################################################################################


function error {
    echo "ERROR: ${*}" >/dev/stderr
}

function error-usage {
    error "${*}"
    echo
    usage
    return 2
}

function usage {
    local name

    name="$(basename "${0}" | tr "-" " ")"

    cat <<EOM
Run a (non-destructive) kubectl command over all contexts.

Usage: ${name} [-h | --help] <CMD> [ARGS]

  -h, --help    Show this help message.

Where CMD is one of:

$(printf '  %s\n' "${!COMMANDS[@]}")

NOTE: ${name} only allows *seemingly* non-destructive commands.
      This only checked through an allow-list so use with caution!

EOM
}

function k8s-logged-in {
    local ctx

    ctx="${1}"

    kubectl --context="${ctx}" --request-timeout 3s auth whoami &>/dev/null
}

function get-contexts {
    kubectl config get-contexts --no-headers -o name
}

function main {
    local ctx cmd
    local -a contexts args

    if [[ " ${*} " == *" --help "* ]] || [[ " ${*} " == *" -h "* ]]; then
        usage
        return
    fi

    cmd="${1:-}"
    if [ -z "${cmd}" ]; then
        error-usage "Missing command!"
    fi
    if [ ! -v "COMMANDS[${cmd}]" ]; then
        error-usage "Unsupported command '${cmd}'!"
    fi

    args=( "${@:2}" )

    mapfile -t contexts < <(get-contexts); wait $!

    echo
    for ctx in "${contexts[@]}"; do
        echo "${ctx^^}"
        echo

        if ! k8s-logged-in "${ctx}"; then
            echo "  Failed to connect!"
            echo
            continue
        fi

        kubectl --context="${ctx}" "${cmd}" "${args[@]}" |& sed 's/^/  /'
        echo
    done
}

main "${@}"; exit
