#!/bin/bash

set -euo pipefail


################################################################################

function usage {
    cat <<EOM
Run a kubectl command over all contexts.

Usage: $(basename "${0}" | tr "-" " ") [-h | --help] <RESOURCE> [ARGS]

  -h, --help    Show this help message.

EOM
}

function get-contexts {
    kubectl config get-contexts --no-headers -o name
}

function main {
    local resource
    local -a contexts

    resource="${1:-}"
    if [ -z "${resource}" ]; then
        usage
        return 2
    fi

    if [[ " ${*} " == *" --help "* ]] || [[ " ${*} " == *" -h "* ]]; then
        usage
        return
    fi

    mapfile -t contexts < <(get-contexts); wait $!

    echo
    for env in "${contexts[@]}"; do
        echo "${env^^}"
        echo

        kubectl --context="${ctx}"                                             \
                get "${resource}" |& sed 's/^/  /'
        echo
    done
}

main "${@}"; exit
